- name: install wireguard
  apt:
    name:
      - wireguard-dkms
      - wireguard-tools
    state: present

- name: generate private and public key  # noqa 503
  shell: |
      set -o pipefail
      wg genkey | tee mesh.key | wg pubkey > mesh.pub
      chmod -v 400 /etc/wireguard/*key
  args:
    executable: /bin/bash
    chdir: /etc/wireguard
    creates: "/etc/wireguard/mesh.pub"
  notify: restart wireguard mesh

- name: cat the public key for setting it as fact  # noqa 301 305
  shell: "cat /etc/wireguard/mesh.pub"
  register: wireguard_mesh_public_key_out

- name: set fact for the public key
  set_fact:
    wireguard_mesh_public_key: "{{ wireguard_mesh_public_key_out.stdout_lines[0] }}"

- name: "template config"
  template:
    src: templates/etc/wireguard/mesh.conf.j2
    dest: "/etc/wireguard/mesh.conf"
    owner: root
    group: root
    mode: 0600
  notify: restart wireguard mesh
